apiVersion: v1
kind: Service
metadata:
  name: todo-app
  labels:
    run: todo-app

spec:
  type: NodePort
  ports:
    - port: 5000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
        - name: todo-app
          image: himanshukingstorm/todo-app-py:latest
          ports:
            - containerPort: 5000
